language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.3
  - 5.6
  - 7
  - hhvm

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=0 WP_PULUGIN_DEPLOY=1
  allow_failures:
    - php: hhvm
    - php: 7



before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit

after_success: curl -L https://raw.githubusercontent.com/miya0001/travis2wpplugin/master/deploy.sh | bash

env:
  matrix:
    - WP_VERSION=4.2.5 WP_MULTISITE=0
    - WP_VERSION=4.2.5 WP_MULTISITE=1
    - WP_VERSION=4.3.1 WP_MULTISITE=0
    - WP_VERSION=4.3.1 WP_MULTISITE=1
    - WP_VERSION=trunk WP_MULTISITE=0
    - WP_VERSION=trunk WP_MULTISITE=1

  global:
    - SVN_REPO: https://plugins.svn.wordpress.org/custom-post-type-permalinks/
    - GH_REF: https://github.com/torounit/custom-post-type-permalinks.git
    - secure: "G6ugr3v6cOwWCh8sDsqn4NfJ74zO68n1xwDmPOjkhMr0jhnwdNcPgQzVA5WXf/8yV5I910UAm3XQrT5CajXgwt2Tcsli67Olu3R8Nqcwh0lqAK5Q4LdD5RoP2Ie2jY/ih4Z56CZEhiuZbG9Qp/YeN8j/kIEDf/y/VwzoX/s3OXI="

